global:
  release: "inspire"
  namespace: "default"
demo:
  init:
    envFile: "/deployment/icm_variables_default.json"
    chsFile: "/deployment/spt_import_process.chs"
    workflows:
      - "SPT Content Import"
      - "SPT Import Handler"
  stage:
    files:
      - src: "/deployment/spt-base.zip"
        dest: "/opt/scalerAdditionalStorage/input/spt-base.zip"
