global:
  release: "inspire"
  namespace: "default"
demo:
  username: "system"
  password: "Password12345*"
  import:
    zipFile: "tmp/spt-loadProcess/step-3/sptDeployment_20220928.zip"
  init:
    envFile: "tmp/spt-loadProcess/step-1/variable_ICM_default.json"
    chsFile: "tmp/spt-loadProcess/step-2/SPT Import Processes.chs"
    workflows:
      - "SPT Content Import"
      - "SPT Import Handler"
